# Generated by Django 2.2.6 on 2021-04-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
