# Generated by Django 2.2.6 on 2021-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите пожалуйста текст вашего комментария', max_length=300, verbose_name='Комментарий'),
        ),
    ]
