# Generated by Django 2.2.6 on 2021-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210323_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите пожалуйста текст вашего комментария', verbose_name='Комментарий'),
        ),
    ]
