# Generated by Django 2.2.6 on 2021-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/avatar180.jpg', upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
