# Generated by Django 2.2.6 on 2021-04-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210402_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/avatar180.jpg', help_text='Добавьте аватарку', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
