# Generated by Django 2.2.6 on 2021-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210403_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/avatar180.jpg', help_text='Добавьте аватарку', upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
