# Generated by Django 2.2.6 on 2021-04-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='recipient',
            field=models.ForeignKey(help_text='Укажите имя получателя', on_delete=django.db.models.deletion.CASCADE, related_name='pm_topics_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(blank=True, default='Без темы', max_length=255, verbose_name='Тема'),
        ),
    ]
