# Generated by Django 2.2.6 on 2021-04-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(blank=True, default='Без темы', max_length=255, null=True, verbose_name='Тема'),
        ),
    ]
